### ISSUE TITLE
API improvement suggestions or convenience API suggestions

### ISSUE THREAD

**Issue by stonko1994** [dscyrescotti/SwiftTheming#25]
Would it be possible to improve the usage of this awesome tool or add a convenience API?

## Room for improvement
IMO the API for simple accessing e.g. a color form a View is pretty tedious. In every View one has to repeat the same 2 steps:

1. Adding the property-wrapper
```swift
@ThemeProviding<Theme> var themeProvider
```

2. Passing the `themeProvider` to the View Modifier
```swift
.foregroundColor(on: themeProvider, for: .foregroundColor)
```

## Suggestion
Wouldn't it be way easier if we could get rid of points 1 and point 2? This would lead to a usage similar to:

```swift
.foregroundColor(.foregroundColor)
```

I saw that there is a lot of generic usage involved which could make this tedious.

## Possible Convenience API
However, what I did in the meantime was to add the above suggestion as an extension to the Package without any internal changes needed.

What I did was creating new `ViewModifier`s that encapsulates adding the PropertyWrapper and the need of passing the `themeProvider` again to the existing `ViewModifier`s.

```swift
struct ThemedForegroundColorViewModifier: ViewModifier {
    @ThemeProviding<Theme> private var themeProvider
    private let asset: Theme.ThemeAsset.ColorAsset

    init(asset: Theme.ThemeAsset.ColorAsset) {
        self.asset = asset
    }

    func body(content: Content) -> some View {
        content
            .foregroundColor(on: themeProvider, for: asset)
    }
}
```

```swift
extension View {
    func foregroundColor(_ asset: Theme.ThemeAsset.ColorAsset) -> some View {
        self.modifier(ThemedForegroundColorViewModifier(asset: asset))
    }
}
```

_Usage would look like exactly the same as above_

### Similar things could be achieved for Color
This requires a separate `View` as we need a custom init.

```swift
struct ThemedColor: View, ShapeStyle {
    @ThemeProviding<Theme> private var themeProvider
    private let asset: Theme.ThemeAsset.ColorAsset

    init(_ asset: Theme.ThemeAsset.ColorAsset) {
        self.asset = asset
    }

    var body: some View {
        Color(on: themeProvider, for: asset)
    }
}
```

The usage would look like this:
```swift
ThemedColor(.backgroundColor)
```

**Comment by dscyrescotti** [comment]
I really appreciate your suggestions to reform declarative side for easy and developer-friendly usage. Actually, I'm also aware of those kinds of issues when I'm using it and agree 100 percent with you. I will take a look and find the ideal approach to enhance api side based on your proposed idea.

**Comment by dscyrescotti** [comment]
As **SwiftTheming** [Version 2.0.0](https://github.com/dscyrescotti/SwiftTheming/releases/tag/v2.0.0) has been released with the enhancement on the API design and developer experience, this issue will be closed. Thanks.
